service: get-countries

provider:
  name: aws
  runtime: nodejs14.x

functions:
  getCountries:
    handler: dataApi/getCountries.handler
    events:
      - http:
          path: get-countries
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline
